import { applyTargets } from './exporter';
import { DEFAULT_MODEL } from './models';
import { uid } from './pipeline';
import type { Project } from './types';

export function defaultProject(): Project {
  return {
    id: uid(),
    brand: {
      name: '',
      notes: '',
      palette: [],
      traits: [],
      dos: [],
      donts: [],
      fonts: {},
      analyzed: false,
    },
    style: {
      style: 'outline',
      strokeWeight: 2,
      corners: 'rounded',
      colorMode: 'brand',
      primary: '#1d1d1f',
      accent: '#2257e6',
      parts: true,
    },
    iconNames: [],
    icons: [],
    references: [],
    runs: [],
    modelId: DEFAULT_MODEL,
    quality: 'low',
    candidates: 2,
    exportOptions: applyTargets({
      targets: ['web', 'design'],
      svg: true,
      png: true,
      pngSizes: [24, 48, 512],
      react: true,
      sprite: false,
      figma: true,
      naming: 'kebab',
      prefix: '',
      pngScales: [1],
      pixelSnap: true,
      emf: false,
      buttons: false,
      buttonSize: 48,
      buttonSkin: 'isa',
      buttonShape: 'square',
      stateColor: '',
      viIcons: false,
      bannerText: '',
      bannerColor: '',
      states: false,
      indicators: false,
      indicatorKinds: ['round-led'],
      indicatorColors: ['#2fb344', '#d62d20'],
      indicatorSize: 32,
    }, ['labview']),
    spent: 0,
    updatedAt: Date.now(),
  };
}
